version: '3'
services:
  proxy:
    build: proxy
    ports:
    - "5000:5000"
    links:
    - mirror
    environment:
    - PORT0=5000
    - REGISTRY_HOST=mirror
    - REGISTRY_PORT=5000
  mirror:
    build: mirror
      
